import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
            height :{
                'material': '970.656px',
                'cards' : '463.312px',
                'rating' : '640px',
                'pic': '300px'
            },
            width: {
                'progress-1': '1%',
                'progress-2': '2%',
                'progress-3': '3%',
                'progress-4': '4%',
                'progress-5': '5%',
                'progress-6': '6%',
                'progress-7': '7%',
                'progress-8': '8%',
                'progress-9': '9%',
                'progress-10': '10%',
                'progress-11': '11%',
                'progress-12': '12%',
                'progress-13': '13%',
                'progress-14': '14%',
                'progress-15': '15%',
                'progress-16': '16%',
                'progress-17': '17%',
                'progress-18': '18%',
                'progress-19': '19%',
                'progress-20': '20%',
                'progress-21': '21%',
                'progress-22': '22%',
                'progress-23': '23%',
                'progress-24': '24%',
                'progress-25': '25%',
                'progress-26': '26%',
                'progress-27': '27%',
                'progress-28': '28%',
                'progress-29': '29%',
                'progress-30': '30%',
                'progress-31': '31%',
                'progress-32': '32%',
                'progress-33': '33%',
                'progress-34': '34%',
                'progress-35': '35%',
                'progress-36': '36%',
                'progress-37': '37%',
                'progress-38': '38%',
                'progress-39': '39%',
                'progress-40': '40%',
                'progress-41': '41%',
                'progress-42': '42%',
                'progress-43': '43%',
                'progress-44': '44%',
                'progress-45': '45%',
                'progress-46': '46%',
                'progress-47': '47%',
                'progress-48': '48%',
                'progress-49': '49%',
                'progress-50': '50%',
                'progress-51': '51%',
                'progress-52': '52%',
                'progress-53': '53%',
                'progress-54': '54%',
                'progress-55': '55%',
                'progress-56': '56%',
                'progress-57': '57%',
                'progress-58': '58%',
                'progress-59': '59%',
                'progress-60': '60%',
                'progress-61': '61%',
                'progress-62': '62%',
                'progress-63': '63%',
                'progress-64': '64%',
                'progress-65': '65%',
                'progress-66': '66%',
                'progress-67': '67%',
                'progress-68': '68%',
                'progress-69': '69%',
                'progress-70': '70%',
                'progress-71': '71%',
                'progress-72': '72%',
                'progress-73': '73%',
                'progress-74': '74%',
                'progress-75': '75%',
                'progress-76': '76%',
                'progress-77': '77%',
                'progress-78': '78%',
                'progress-79': '79%',
                'progress-80': '80%',
                'progress-81': '81%',
                'progress-82': '82%',
                'progress-83': '83%',
                'progress-84': '84%',
                'progress-85': '85%',
                'progress-86': '86%',
                'progress-87': '87%',
                'progress-88': '88%',
                'progress-89': '89%',
                'progress-90': '90%',
                'progress-91': '91%',
                'progress-92': '92%',
                'progress-93': '93%',
                'progress-94': '94%',
                'progress-95': '95%',
                'progress-96': '96%',
                'progress-97': '97%',
                'progress-98': '98%',
                'progress-99': '99%',
                'progress-100': '100%',
                'pic' : '300px'
              }
        },
    },

    plugins: [forms
    ],
};
